export enum AdsStatus {
  ACTIVE = "ACTIVE",
  DONE = "DONE",
  IN_RENT = "IN_RENT",
  RESERVED = "RESERVED",
  DISCONTINUED = "DISCONTINUED",
  DELETED = "DELETED",
  DRAFT = "DRAFT",
  AWAITING_FOR_ACTIVATION = "AWAITING_FOR_ACTIVATION"
}
